#!/bin/bash
# InfraCanvas Agent Installer
# Usage: curl -fsSL https://github.com/YOUR_ORG/InfraCanvas/releases/latest/download/install.sh | bash
# Or with overrides:
#   bash install.sh --backend-url wss://custom-relay.example.com --name my-vm

set -euo pipefail

# ── defaults ──────────────────────────────────────────────────────────────────
# Set DEFAULT_RELAY_URL to your hosted relay domain after deployment.
# Users can still override with --backend-url or INFRACANVAS_BACKEND_URL env var.
DEFAULT_RELAY_URL="ws://localhost:8080"   # ← update to wss://yourdomain.com after adding TLS

BACKEND_URL="${INFRACANVAS_BACKEND_URL:-$DEFAULT_RELAY_URL}"
AGENT_NAME="${INFRACANVAS_AGENT_NAME:-}"
AUTH_TOKEN="${INFRACANVAS_TOKEN:-}"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/infracanvas"
SERVICE_NAME="infracanvas-agent"
GITHUB_REPO="bytestrix/InfraCanvas"
VERSION="latest"

# ── helpers ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend-url) BACKEND_URL="$2"; shift 2;;
    --token)       AUTH_TOKEN="$2";  shift 2;;
    --name)        AGENT_NAME="$2";  shift 2;;
    --version)     VERSION="$2";     shift 2;;
    --install-dir) INSTALL_DIR="$2"; shift 2;;
    *) error "Unknown argument: $1";;
  esac
done

[[ -z "$BACKEND_URL" ]] && error "No relay URL configured. Set DEFAULT_RELAY_URL in the script or pass --backend-url wss://relay.example.com"
[[ -z "$AGENT_NAME" ]] && AGENT_NAME="$(hostname -s)"

# ── detect platform ───────────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  ARCH="amd64";;
  aarch64|arm64) ARCH="arm64";;
  *) error "Unsupported architecture: $ARCH";;
esac
[[ "$OS" != "linux" ]] && error "This installer only supports Linux. For macOS, use: brew install infracanvas"

info "Detected platform: $OS/$ARCH"

# ── check dependencies ────────────────────────────────────────────────────────
for cmd in curl tar; do
  command -v "$cmd" &>/dev/null || error "$cmd is required but not installed"
done

# ── download binary ───────────────────────────────────────────────────────────
BINARY_NAME="infracanvas-${OS}-${ARCH}"
DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/${VERSION}/download/${BINARY_NAME}"

info "Downloading InfraCanvas agent..."
TMP_DIR="$(mktemp -d)"
trap "rm -rf $TMP_DIR" EXIT

if ! curl -fsSL --progress-bar "$DOWNLOAD_URL" -o "$TMP_DIR/infracanvas"; then
  # Fallback: build from source if release not found
  warn "Release binary not found, checking for local build..."
  if [[ -f "$(dirname "$0")/bin/infracanvas-linux-amd64" ]]; then
    cp "$(dirname "$0")/bin/infracanvas-linux-amd64" "$TMP_DIR/infracanvas"
    info "Using local build"
  else
    error "Could not find binary. Build with: make build-all"
  fi
fi

chmod +x "$TMP_DIR/infracanvas"

# ── install binary ────────────────────────────────────────────────────────────
NEED_SUDO=""
[[ ! -w "$INSTALL_DIR" ]] && NEED_SUDO="sudo"

info "Installing to $INSTALL_DIR/infracanvas..."
$NEED_SUDO mv "$TMP_DIR/infracanvas" "$INSTALL_DIR/infracanvas"

# ── write env file ────────────────────────────────────────────────────────────
info "Writing config to $CONFIG_DIR/agent.env..."
$NEED_SUDO mkdir -p "$CONFIG_DIR"
$NEED_SUDO tee "$CONFIG_DIR/agent.env" > /dev/null <<EOF
# InfraCanvas Agent Environment
# Auto-generated by install-agent.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
INFRACANVAS_BACKEND=$BACKEND_URL
INFRACANVAS_TOKEN=$AUTH_TOKEN
INFRACANVAS_SCOPE=host,docker,kubernetes
EOF
$NEED_SUDO chmod 600 "$CONFIG_DIR/agent.env"

# ── install systemd service (if available) ────────────────────────────────────
if command -v systemctl &>/dev/null && [[ -d /etc/systemd/system ]]; then
  info "Installing systemd service..."
  $NEED_SUDO tee "/etc/systemd/system/${SERVICE_NAME}.service" > /dev/null <<EOF
[Unit]
Description=InfraCanvas Infrastructure Discovery Agent
Documentation=https://github.com/${GITHUB_REPO}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${CONFIG_DIR}/agent.env
ExecStart=${INSTALL_DIR}/infracanvas start
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=infracanvas-agent

[Install]
WantedBy=multi-user.target
EOF

  $NEED_SUDO systemctl daemon-reload
  $NEED_SUDO systemctl enable "$SERVICE_NAME"
  $NEED_SUDO systemctl restart "$SERVICE_NAME"

  echo ""
  echo -e "${GREEN}✓ Agent installed and started as systemd service${NC}"
  echo ""
  echo "  View logs:    sudo journalctl -u $SERVICE_NAME -f"
  echo "  Stop agent:   sudo systemctl stop $SERVICE_NAME"
  echo "  Restart:      sudo systemctl restart $SERVICE_NAME"
  echo ""

  # Wait a moment then grab the pair code from logs
  sleep 5
  PAIR_CODE=$(journalctl -u "$SERVICE_NAME" --no-pager -n 300 2>/dev/null | grep -v "Endpoints is deprecated" | grep -oP 'Pair code: \K[A-Z]+-[A-Z]+-\d+' | tail -1 || true)
  if [[ -n "$PAIR_CODE" ]]; then
    echo -e "${GREEN}════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Your pair code:  ${YELLOW}${PAIR_CODE}${NC}"
    echo -e "${GREEN}  Enter this in the InfraCanvas dashboard${NC}"
    echo -e "${GREEN}════════════════════════════════════════${NC}"
  else
    echo "  Get pair code: sudo journalctl -u $SERVICE_NAME -n 300 | grep -v 'deprecated' | grep 'Pair code'"
  fi

else
  # No systemd — start in background
  info "systemd not available, starting agent in background..."
  set -a; source "$CONFIG_DIR/agent.env"; set +a
  nohup "$INSTALL_DIR/infracanvas" start \
    > /var/log/infracanvas-agent.log 2>&1 &
  echo $! | $NEED_SUDO tee /var/run/infracanvas-agent.pid > /dev/null

  sleep 3
  PAIR_CODE=$(grep -oP 'Pair code: \K[A-Z]+-[A-Z]+-\d+' /var/log/infracanvas-agent.log | tail -1 || true)
  echo ""
  echo -e "${GREEN}✓ Agent started (PID: $(cat /var/run/infracanvas-agent.pid 2>/dev/null))${NC}"
  echo ""
  if [[ -n "$PAIR_CODE" ]]; then
    echo -e "${GREEN}════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Your pair code:  ${YELLOW}${PAIR_CODE}${NC}"
    echo -e "${GREEN}  Enter this in the InfraCanvas dashboard${NC}"
    echo -e "${GREEN}════════════════════════════════════════${NC}"
  else
    echo "  View logs:     tail -f /var/log/infracanvas-agent.log"
    echo "  Get pair code: grep 'Pair code' /var/log/infracanvas-agent.log"
  fi
fi
